# Generated by tinty from ~/.config/tinted-theming/templates/plot.mustache — do not edit.
# Imported by ~/.config/nushell/modules/plot/theme.nu via `use colors.nu *`.
# Provides the full Rosé Pine palette so gnuplot output matches every other tool.
#
# Series order (extensive — 12 colors): alternates cool / warm / neutral so
# adjacent series contrast strongly. base0D (sky blue) leads as the structural
# anchor, matching nushell commands & ls executables.

export const PLOT_STYLE = {
  background: '#191724'  # deep cobalt night sky — pane bg
  foreground: '#e0def4'  # village wall cream — warm fg (the yellow wash)
  grid:       '#26233a'  # swirl shadow — subtle gridlines
  border:     '#6e6a86'  # swirl mid — axes / borders one step brighter than grid
  muted:      '#8c88a6'  # swirl bright — minor ticks / hints
  font:       'MesloLGL Nerd Font,10'  # matches terminal (ghostty)
  size:       [1400, 800]
  # 12-color series cycle. Hue/luminance steps chosen so neighbors don't blend.
  series: [
    '#c4a7e7'  # sky blue       — structural backbone
    '#ebbcba'  # star yellow    — saturated gold
    '#31748f'  # hill sage      — cool green
    '#f6c177'  # twilight indigo — lavender pop
    '#ffaace'  # bright moon    — warm peach
    '#9ccfd8'  # swirl cyan
    '#f6c177'  # honey amber    — deep warm
    '#fff2a3'  # bright indigo
    '#609fbb'  # bright sage
    '#eb6f92'  # moon amber
    '#fff0ee'  # bright star    — brightest cream-yellow
    '#524f67'  # pale sky       — neutral cool
  ]
}
