# Starry Cat — the plot theme.
#
# Color values are NOT defined here. They come from `colors.nu`, generated by
# tinty from the starry-cat scheme (`~/.config/tinted-theming/`). To change a
# color, edit the palette via the starry-cat skill and run `starry-cat rebuild`
# so plot output stays in sync with every other tool. This file only adapts
# `PLOT_STYLE` onto the shapes the Vega-Lite backend (`vega.nu`) consumes.

use ./colors.nu *

export def main []: nothing -> record {
    {
        bg: $PLOT_STYLE.background
        fg: $PLOT_STYLE.foreground
        grid: $PLOT_STYLE.grid
        border: $PLOT_STYLE.border
        muted: $PLOT_STYLE.muted
        series: $PLOT_STYLE.series
        font: $PLOT_STYLE.font
    }
}

# Vega-Lite `config` block: applies the starry-cat palette to every chart the
# backend renders. Per-encoding settings (axis titles, grid toggle, legend
# position) are layered on top of this by `vega.nu`.
export def "vega-config" []: nothing -> record {
    let t = main
    {
        background: $t.bg
        view: { stroke: null }
        title: { color: $t.fg, fontSize: 14, anchor: "start" }
        axis: {
            domainColor: $t.border
            tickColor: $t.border
            gridColor: $t.grid
            gridOpacity: 0.5
            labelColor: $t.fg
            titleColor: $t.fg
        }
        legend: { labelColor: $t.fg, titleColor: $t.fg }
        range: { category: $t.series }
        mark: { color: ($t.series | first) }
        line: { strokeWidth: 2 }
        point: { filled: true }
    }
}
