# Reflects AI-agent state in an event-driven on-disk store, and projects that
# store onto the zellij pane/tab titles. Submodule of `ai`; commands are
# `ai agent-notify <cmd>`. The macOS SketchyBar surface is the `render/`
# submodule (`ai agent-notify render ...`), driven by thin glue scripts in the
# bar's config; the frontend poke lives in the hook glue, not here. `browse` is
# the terminal-side twin of those drawers: pick a live agent, land in its pane —
# both surfaces derive their rows from lib/view.nu, so they cannot drift.
#
#  - Pane title: "<glyph> <base>" — a small state indicator on the pane name.
#  - Tab title:  a bare AGGREGATE over every agent pane in the tab ("▴ •2 base").
#
# A tab's BASE name belongs to the user, not to us: every projection reads it back
# from the LIVE tab title (markers stripped), so neither a rename we write nor the
# last agent leaving can erase it — and a manual rename is picked up for free.
#
# STATE flows from Claude Code hooks → verbs below → per-pane store records
# (see lib/store.nu). Surfaces are pure projections. There is NO periodic scan:
# a normal exit drops its record (SessionEnd → clear); an abruptly-killed pane is
# GC'd by `reconcile` (a slow liveness janitor run from the bar), which is the
# only place zellij is scanned. Each verb reads its Claude Code hook payload from
# the pipeline ($in), and is a no-op outside zellij ($ZELLIJ_PANE_ID).

use lib/state.nu *
use lib/title.nu *
use lib/zellij.nu *
use lib/store.nu
use lib/project.nu *
use lib/janitor.nu *
use lib/transcript.nu
use lib/picker.nu *
export use jump.nu *
export use render/

# Notification types that are genuinely "the agent needs YOU" (others — idle
# nudges, auth success, elicitation acks — must NOT escalate to needs-attention).
const ATTN_NOTIFS = ["permission_prompt" "elicitation_dialog" "elicitation_url_dialog" "agent_needs_input"]

# This pane's identity, from the env a hook inherits from Claude. null off-zellij.
def my-ids [] {
    let s = $env.ZELLIJ_SESSION_NAME? | default ""
    let p = $env.ZELLIJ_PANE_ID? | default ""
    if ($s | is-empty) or ($p | is-empty) { null } else { {session: $s, pane_id: ($p | into int)} }
}

# A pane base is usable iff it's non-empty and NOT Claude Code's own OSC title
# ("✳ Claude Code"): that self-title is not a real name. `str contains` (not
# `==`) so status-suffixed variants and already-stored junk both self-heal.
def usable-base [name: any] {
    let t = ($name | default "" | str trim)
    ($t != "") and (not ($t | str contains "Claude Code"))
}

# The autogenerated pane name = the agent's cwd basename (from the hook payload).
def cwd-base [p: record] {
    let c = ($p.cwd? | default "")
    if ($c | is-empty) { "" } else { $c | path basename }
}

# Upsert this pane's record with `changes`, then project pane + tab titles.
#
# A pane's base name is chosen ONCE and then frozen. `auto` (the cwd basename) is
# only ever provisional: it labels the pane until the agent names itself. The
# first explicit `name` (the CLAUDE.md session naming) replaces it and LOCKS the
# base — every later name, provisional or explicit, is ignored from then on, so
# the pane never renames itself out from under you. We never read the live pane
# title back: for a Claude pane that's its own OSC title, not a name.
def apply [agent: string, changes: record, name?: any, auto?: any] {
    let ids = my-ids
    if ($ids == null) { return }
    let existing = store get $ids.session $ids.pane_id
    let info = pane-tab-info $ids.session $ids.pane_id

    let locked = ($existing.pane_locked? | default false)
    let naming = (not $locked) and (usable-base $name)
    let base = if $locked { $existing.pane_name | str trim
        } else if $naming { $name | str trim
        } else if (usable-base ($existing.pane_name?)) { $existing.pane_name | str trim
        } else if (usable-base $auto) { $auto | str trim
        } else { "" }

    let rec = ($existing | default {})
        | merge {session: $ids.session, pane_id: $ids.pane_id, agent: $agent, pane_name: $base, pane_locked: ($locked or $naming)}
        | merge (if ($info != null) { {tab_id: $info.tab_id, tab_name: (tab-base $info.tab_name ($existing.tab_name?)), tab_position: $info.tab_position} } else { {} })
        | merge $changes
    store put $rec

    rename-pane $ids.session $ids.pane_id (bare-title (glyph-of ($rec.state? | default "idle")) $base)
    if ($rec.tab_id? != null) { project-tab $ids.session $rec.tab_id (store list) (if ($info != null) { $info.tab_name } else { null }) }
}

# ── Hook-facing verbs (payload piped in via $in; empty when called manually) ──

# SessionStart: capture identity. Don't clobber a live state on compact/resume.
export def session-start [agent: string, name?: string] {
    let p = $in | default {}
    let ids = my-ids
    if ($ids == null) { return }
    let existing = store get $ids.session $ids.pane_id
    let keep = (($p.source? | default "startup") in ["compact" "resume"]) and ($existing != null)
    apply $agent {
        state: (if $keep { $existing.state? | default "idle" } else { "idle" })
        transcript: ($p.transcript_path? | default (($existing.transcript?) | default ""))
        preview: (if $keep { $existing.preview? | default "" } else { "" })
    } $name (cwd-base $p)
}

# "◦" working — busy. Idempotent: skip the zellij/title work if already working.
export def working [agent: string] {
    let p = $in | default {}
    let ids = my-ids
    if ($ids == null) { return }
    let existing = store get $ids.session $ids.pane_id
    if ($existing != null) and (($existing.state?) == "working") { return }
    apply $agent {state: "working", preview: ""} null (cwd-base $p)
}

# "•" awaiting — your turn. Preview = the agent's last message.
export def awaiting [agent: string] {
    let p = $in | default {}
    let ids = my-ids
    if ($ids == null) { return }
    let existing = store get $ids.session $ids.pane_id
    let msg = $p.last_assistant_message? | default ""
    let preview = if (($msg | str trim) != "") {
        $msg
    } else {
        transcript last-message (($p.transcript_path?) | default (($existing.transcript?) | default ""))
    }
    apply $agent {state: "awaiting", preview: ($preview | str trim)} null (cwd-base $p)
}

# "▴" needs-attention — blocked on YOU. Only genuine input-needed notifications
# escalate; the message is the preview ("what does it need from me?").
export def needs-attention [agent: string] {
    let p = $in | default {}
    let nt = $p.notification_type? | default ""
    if ($nt != "") and ($nt not-in $ATTN_NOTIFS) { return }
    apply $agent {state: "needs-attention", preview: (($p.message? | default "") | str trim)} null (cwd-base $p)
}

# SessionEnd / manual: drop this pane's record and recompute its tab, which
# leaves both surfaces bare — the pane's own name, the tab's own name, no glyph.
export def clear [agent?: string] {
    let ids = my-ids
    if ($ids == null) { return }
    let rec = store get $ids.session $ids.pane_id
    store drop $ids.session $ids.pane_id
    try { rename-pane $ids.session $ids.pane_id (bare-title "" (($rec.pane_name?) | default "")) }
    if ($rec != null) and ($rec.tab_id? != null) { project-tab $ids.session $rec.tab_id (store list) null }
}

# ── Query verbs (read by the SketchyBar plugin: sketchybar → ai) ──

# All agent records (store-only; no scan). The bar's instant-refresh path.
export def list [] { store list }

# The preview text ("what does it need from me?") for one agent. "" if unknown.
export def preview [session: string, pane_id: int] {
    let r = store get $session $pane_id
    if ($r == null) { "" } else { $r.preview? | default "" }
}

# Liveness janitor (slow bar timer): GC records whose pane died abruptly, fixing
# their tabs, then return the survivors.
export def reconcile [] { gc }

# ── Interactive ──────────────────────────────────────────────────────────────

# Browse the live agents (state, name, message) and jump to the one you pick —
# the same effect as clicking its row in a SketchyBar drawer. `query` prefilters
# the list. Reconciles first, so a pane that died abruptly is never offered.
export def browse [query?: string] {
    let chosen = pick (gc) $query
    if ($chosen == null) { return }
    jump $chosen.session $chosen.pane_id
}
