# Reflects AI-agent state in an event-driven on-disk store, and projects that
# store onto the zellij pane/tab titles. Submodule of `ai`; commands are
# `ai agent-notify <cmd>`. The macOS SketchyBar surface is the `render/`
# submodule (`ai agent-notify render ...`), driven by thin glue scripts in the
# bar's config; the frontend poke lives in the hook glue, not here. `browse` is
# the terminal-side twin of those drawers: pick a live agent, land in its pane —
# both surfaces derive their rows from lib/view.nu, so they cannot drift. It is
# skim (`sk`, from nu_plugin_skim) in a scratch floating pane, the terminal's
# answer to a drawer.
#
#  - Pane title: "<glyph> <base>" — a small state indicator on the pane name.
#  - Tab title:  a bare AGGREGATE over every agent pane in the tab ("▴ •2 base").
#
# A tab's BASE name belongs to the user, not to us: every projection reads it back
# from the LIVE tab title (markers stripped), so neither a rename we write nor the
# last agent leaving can erase it — and a manual rename is picked up for free.
#
# STATE flows from Claude Code hooks → verbs below → per-pane store records
# (see lib/store.nu). Surfaces are pure projections. There is NO periodic scan:
# a normal exit drops its record (SessionEnd → clear); an abruptly-killed pane is
# GC'd by `reconcile` (a slow liveness janitor run from the bar), which is the
# only place zellij is scanned. Each verb reads its Claude Code hook payload from
# the pipeline ($in), and is a no-op outside zellij ($ZELLIJ_PANE_ID).

use lib/state.nu *
use lib/title.nu *
use lib/zellij.nu *
use lib/store.nu
use lib/project.nu *
use lib/janitor.nu *
use lib/transcript.nu
use lib/markdown.nu
use lib/picker.nu *
export use jump.nu *
export use render/

# Notification types that are genuinely "the agent needs YOU" (others — idle
# nudges, auth success, elicitation acks — must NOT escalate to needs-attention).
const ATTN_NOTIFS = ["permission_prompt" "elicitation_dialog" "elicitation_url_dialog" "agent_needs_input"]

# This pane's identity, from the env a hook inherits from Claude. null off-zellij.
def my-ids [] {
    let s = $env.ZELLIJ_SESSION_NAME? | default ""
    let p = $env.ZELLIJ_PANE_ID? | default ""
    if ($s | is-empty) or ($p | is-empty) { null } else { {session: $s, pane_id: ($p | into int)} }
}

# A pane base is usable iff it's non-empty and NOT Claude Code's own OSC title
# ("✳ Claude Code"): that self-title is not a real name. `str contains` (not
# `==`) so status-suffixed variants and already-stored junk both self-heal.
def usable-base [name: any] {
    let t = ($name | default "" | str trim)
    ($t != "") and (not ($t | str contains "Claude Code"))
}

# The autogenerated pane name = the agent's cwd basename (from the hook payload).
def cwd-base [p: record] {
    let c = ($p.cwd? | default "")
    if ($c | is-empty) { "" } else { $c | path basename }
}

# Upsert this pane's record with `changes`, then project pane + tab titles.
#
# A pane's base name is chosen ONCE and then frozen. `auto` (the cwd basename) is
# only ever provisional: it labels the pane until the agent names itself. The
# first explicit `name` (the CLAUDE.md session naming) replaces it and LOCKS the
# base — every later name, provisional or explicit, is ignored from then on, so
# the pane never renames itself out from under you. We never read the live pane
# title back: for a Claude pane that's its own OSC title, not a name.
def apply [agent: string, changes: record, name?: any, auto?: any] {
    let ids = my-ids
    if ($ids == null) { return }
    let existing = store get $ids.session $ids.pane_id
    let info = pane-tab-info $ids.session $ids.pane_id

    let locked = ($existing.pane_locked? | default false)
    let naming = (not $locked) and (usable-base $name)
    let base = if $locked { $existing.pane_name | str trim
        } else if $naming { $name | str trim
        } else if (usable-base ($existing.pane_name?)) { $existing.pane_name | str trim
        } else if (usable-base $auto) { $auto | str trim
        } else { "" }

    let rec = ($existing | default {})
        | merge {session: $ids.session, pane_id: $ids.pane_id, agent: $agent, pane_name: $base, pane_locked: ($locked or $naming)}
        | merge (if ($info != null) { {tab_id: $info.tab_id, tab_name: (tab-base $info.tab_name ($existing.tab_name?)), tab_position: $info.tab_position} } else { {} })
        | merge $changes
    store put $rec

    rename-pane $ids.session $ids.pane_id (bare-title (glyph-of ($rec.state? | default "idle")) $base)
    if ($rec.tab_id? != null) { project-tab $ids.session $rec.tab_id (store list) (if ($info != null) { $info.tab_name } else { null }) }
}

# ── Hook-facing verbs (payload piped in via $in; empty when called manually) ──

# SessionStart: capture identity. Don't clobber a live state on compact/resume.
export def session-start [agent: string, name?: string] {
    let p = $in | default {}
    let ids = my-ids
    if ($ids == null) { return }
    let existing = store get $ids.session $ids.pane_id
    let keep = (($p.source? | default "startup") in ["compact" "resume"]) and ($existing != null)
    apply $agent {
        state: (if $keep { $existing.state? | default "idle" } else { "idle" })
        transcript: ($p.transcript_path? | default (($existing.transcript?) | default ""))
        preview: (if $keep { $existing.preview? | default "" } else { "" })
        preview_md: (if $keep { $existing.preview_md? | default "" } else { "" })
    } $name (cwd-base $p)
}

# "◦" working — busy. Idempotent: skip the zellij/title work if already working.
export def working [agent: string] {
    let p = $in | default {}
    let ids = my-ids
    if ($ids == null) { return }
    let existing = store get $ids.session $ids.pane_id
    if ($existing != null) and (($existing.state?) == "working") { return }
    apply $agent {state: "working", preview: "", preview_md: ""} null (cwd-base $p)
}

# "•" awaiting — your turn. Preview = the agent's last message, stored TWICE
# (lib/markdown.nu): `preview` flattened out of markdown for the bar, whose labels
# take one font and one colour, and `preview_md` as written, because the picker's
# preview pane renders ANSI and can show the styling. The flattening keeps the
# LINE STRUCTURE, which is what the bar lays out with `preview-lines`; the picker
# renders the markdown at the width of the pane it lands in.
export def awaiting [agent: string] {
    let p = $in | default {}
    let ids = my-ids
    if ($ids == null) { return }
    let existing = store get $ids.session $ids.pane_id
    let msg = $p.last_assistant_message? | default ""
    let preview = if (($msg | str trim) != "") {
        $msg
    } else {
        transcript last-message (($p.transcript_path?) | default (($existing.transcript?) | default ""))
    }
    apply $agent {state: "awaiting", preview: (markdown to-plain $preview), preview_md: $preview} null (cwd-base $p)
}

# "▴" needs-attention — blocked on YOU. Only genuine input-needed notifications
# escalate; the message is the preview ("what does it need from me?").
export def needs-attention [agent: string] {
    let p = $in | default {}
    let nt = $p.notification_type? | default ""
    if ($nt != "") and ($nt not-in $ATTN_NOTIFS) { return }
    let msg = $p.message? | default ""
    apply $agent {state: "needs-attention", preview: (markdown to-plain $msg), preview_md: $msg} null (cwd-base $p)
}

# SessionEnd / manual: drop this pane's record and recompute its tab, which
# leaves both surfaces bare — the pane's own name, the tab's own name, no glyph.
export def clear [agent?: string] {
    let ids = my-ids
    if ($ids == null) { return }
    let rec = store get $ids.session $ids.pane_id
    store drop $ids.session $ids.pane_id
    try { rename-pane $ids.session $ids.pane_id (bare-title "" (($rec.pane_name?) | default "")) }
    if ($rec != null) and ($rec.tab_id? != null) { project-tab $ids.session $rec.tab_id (store list) null }
}

# ── Query verbs (read by the SketchyBar plugin: sketchybar → ai) ──

# All agent records (store-only; no scan). The bar's instant-refresh path.
export def list [] { store list }

# The preview text ("what does it need from me?") for one agent. "" if unknown.
export def preview [session: string, pane_id: int] {
    let r = store get $session $pane_id
    if ($r == null) { "" } else { $r.preview? | default "" }
}

# Liveness janitor (slow bar timer): GC records whose pane died abruptly, fixing
# their tabs, then return the survivors.
export def reconcile [] { gc }

# ── Interactive ──────────────────────────────────────────────────────────────

# Where `use ai` resolves from, baked in at parse time: the scratch pane's nu is
# started with `-n` (no config, so no $env.NU_LIB_DIRS to inherit) and has to be
# pointed back at this repo explicitly.
const LIB_DIR = path self ../..

# The scratch pane's nu is started with `-n`: no config, so no module hooks, no
# skim palette — and no plugin registry either. All three live somewhere this
# shell can reach and that one cannot, so they are handed over at launch: the
# plugin as a binary path read out of OUR registry (no second copy to keep in
# step), the other two as `source` lines for the files config.nu itself sources.
#
# Every one of them is optional. Without the plugin the hooks have no engines and
# the module falls back to the built-in `input list` and to unstyled text, both
# of which need nothing — a missing piece costs a preview pane or its colours,
# never the pane's ability to run.
def skim-binary [] { plugin list | where name == "skim" | get -o 0.filename }

def config-sources [] {
    [module-hooks.nu skim-colors.nu]
    | each {|f| $nu.default-config-dir | path join $f }
    | where {|f| $f | path exists }
    | each {|f| $"source ($f | to nuon); " }
    | str join
}

# Browse the live agents (state, name, message) and jump to the one you pick —
# the same effect as clicking its row in a SketchyBar drawer. `query` prefills
# the picker's prompt. Reconciles first, so a pane that died abruptly is never
# offered.
#
# The picker is fired into a SCRATCH FLOATING pane rather than run in the pane
# you called it from: a drawer is what this is, so it gets a surface of its own —
# and the pane closes itself on the jump. The launcher returns at once; `--here`
# is the other half, the in-pane run (and the escape hatch when there is no
# zellij to float in, where it simply runs inline).
#
# A message longer than the preview pane is never truncated, only unscrolled:
# with a picker that HAS a preview pane (see the `picker` hook), ctrl-up and
# ctrl-down move it a line, ctrl-u and ctrl-d a page (as in nvim), and shift-up,
# shift-down or the mouse wheel over the pane do what skim ships. The bindings
# live with the engine, in ~/.config/nushell/module-hooks.nu, so every preview in
# every module scrolls the same way — and they are ctrl, not alt, because zellij
# keeps alt-h/j/k/l for pane focus and never forwards them.
export def browse [query?: string, --here] {
    if $here or ((my-ids) == null) {
        let chosen = pick (gc) $query
        if ($chosen == null) { return }
        jump $chosen.session $chosen.pane_id
        return
    }
    # Store-only pre-check (no gc — that is the pane's job): an empty store is
    # the one case a floating pane would just flash, so answer it in place.
    if (store list | is-empty) { print $"(ansi dark_gray)no agents(ansi reset)"; return }
    # `to nuon` quotes the query back into the inner source — a name with a space
    # (or a quote) survives the round trip intact.
    let q = $query | default "" | to nuon
    let skim = skim-binary
    let plugin = if ($skim == null) { [] } else { ["--plugins" $skim] }
    let inner = (config-sources) + "use ai; ai agent-notify browse --here " + $q
    float-run "agents" [$nu.current-exe "-n" ...$plugin "-I" $LIB_DIR "-c" $inner]
}
